export default {
  // The URL we're connecting to
  hostname: 'http://localhost:3004', // path for proxy server
  apiHostName: 'http://localhost:8080/VulhuntApi',
  // API layer
  // Map shortnames to the actual endpoints, so that we can use them in the middleware
  endpoints: {
    // vulhunt apis
    register: '/before/account/register',
    registerAdmin: '/before/account/register/client',
    // login: '/before/account/get/login',
    login: '/users',
    verifyOtp: '/before/account/verify/otp',
    resendOtp: '/before/account/generate/otp',
    verifyOtpFromAccount: 'account/verify/otp',
    resendOtpFromAccount: 'account/generate/otp',

    requestKYC: '/digio/request/kyc',
    getAadharVerifiedStatus: 'onboard/get/aadhaar/status',
    updateKycStatus: '/digio/update/kyc/status',
    getCampaignTargetType: 'campaign/get/target/types',

    // vulhunt apis after login
    updateAccountInfo: '/onboard/account',
    getAccountInfo: '/onboard/account',
    setCampaignTargetDetails: '/campaign/saveupdate/target/details',
    getCampaignTargetDetails: '/campaign/get/target/details',

    // seeder apis for reference
    users: 'users',
    deleteUser: '/users',
    getUser: '/users',
    // sendotp: '/before/account/reset/password',
    forgotPasswordLink: '/before/account/reset/password',
    checkLinkStatus: '/before/account/get/reset/link/status',
    resetPassword: '/before/account/reset/password',
    verifyotp: '/api/accounts/password/reset/email',
    // register: '/api/account/register',
    // login: 'consumer/api/token',
    changePassword: '/api/accounts/password/change',
    updateBasicDeails: '/api/accounts/profile/update',
    BOOKLIST: '/book/list',
    fetchOffers: '/api/offers/guest/offers',
    suscribeToOffers: '/api/offers/accept',
    featchWallet: '/api/accounts/wallet/cards',
    getOrderHistory: '/api/receipts/list',
    getOrderDetails: '/api/receipts/ticketId',
    verifyPhoneNumber: '/api/accounts/verifyPhoneNumber',
    create_profile: '/api/accounts/profile/create',
    addSocialMedia: '/onboard/saveupdate/user/social',
    getSocialMedia: '/onboard/get/usersocial/details',
    getBankDetails: '/onboard/get/userbank/details',
    setBankDetails: '/onboard/saveupdate/user/bank',
    getPanData: '/onboard/get/user/pan',
    getProfessional: '/onboard/profession',
    addProfessional: '/onboard/profession',
    getCertificateAuthorityList: '/onboard/get/certificateAuthorityList',
    getCampaignTypes: '/campaign/fetch/campignType',
    getVulnerabilityDisclosure: '/campaign/fetch/vulDisc',
    setCampaignDetails: '/campaign/add',
    getCampaignDetails: '/campaign/get',
    setCampaignTarget: '/campaign/saveupdate/targets',
    getCampaignTarget: '/campaign/get/targets',
    getCampaignRewards: '/campaign/get/rewards',
    setCampaignRewards: '/campaign/saveupdate/rewards',
    getSeverityList: '/campaign/get/severity/list',
    getCampaignList: '/campaign/list',
    getSearchList: 'campaign/get/invite',
    getAddInviteList: 'campaign/add/invite',
    addScope: 'campaign/uploadScope',
    searchCampaignList: 'campaign/list',
    getInviteList: 'campaign/get/inviteUsers',
    getScope: 'campaign/get/scopeFile',
    getVulnerabilityDetailsAndFiles: 'vulnerablity/get/details',
    getVulnerabilityList: 'vulnerablity/list',
    getCriticalList: 'vulnerablity/criticalList',
    getSearchVulnerabilityList: 'vulnerablity/list',
    getSortedList: 'vulnerablity/list',
    getCategory: 'vulnerablity/get/category',
    addReport: 'vulnerablity/report',
    setacceptRejectVulnerability: 'vulnerablity/update/status',
    addComment: 'vulnerablity/addComment',
    getComments: 'vulnerablity/getComments',
    publishCampaign: 'campaign/publish',
    getSortedCampaignList: 'campaign/list',
    approveVulnerability: 'campaign/update/enroll/request',
    getSortbyComment: 'vulnerablity/getComments',
    getResearcherList: 'researcher/get/list',
    searchResearcherList: 'researcher/get/list',
    getSortedResearcherList: 'researcher/get/list',
    getResearcherDetails: 'researcher/get/details',
    getResearcherSummary: 'researcher/get/summary',
    generateRefferalCode: 'onboard/generate/referral/code',
    sendReferralCode: 'onboard/send/referral/code',
    getResearcherCampaignList: 'researcher/get/campaigns',
    getResearcherVulnerabilitiesList: 'researcher/get/vulList',
    addProfilePic: 'account/addProfilePic',
    removeProfilePic: 'account/removeProfilePic',
    getParticipants: 'campaign/get/invitedOrEnrolled',
    updateParticipants: 'campaign/update/invitedOrEnrolled',
    getpiechartdata: '/dashboard/get/vuln/submission/report',
    getStackedBarChartData: '/dashboard/get/vuln/scaled/report',
    getCampaignActivityData: '/dashboard/get/campaign/activity/report',
    getClientAcitivityData: '/dashboard/get/client/activity/report',
    getCriticality: 'vulnerablity/criticalList',
    updatePayment: '/razorpay/save/payment/details',
    getTransactionList: 'razorpay/get/transactions',
    getTransactionDetails: 'razorpay/get/transaction/details',
    getVelnerabilityDupicateList: 'vulnerablity/duplicate/list',
    updateVulnerabilities: 'vulnerablity/update/reward/status',
    addPayout: 'razorpay/initiate/payout',
    getSecurityResearcherPerfectionGraph:
      '/dashboard/get/researcher/perfection/report',
    getConsistencyGraph: '/dashboard/get/researcher/vuln/report',
    getPaymentInfo: '/dashboard/get/org/transactions/report',
    getProfilePic: 'download/file/profile/pic',
    getResearcherCertificateList: '/researcher/get/list/certificateAuthority',
    createOrg: 'account/register',
    getOrganizationList: 'account/get/clients',
    searchOrganizationList: 'account/get/clients',
    getReferralData: '/dashboard/get/researcher/referal/report',
    downloadFile: '/download/file',
    getCaptcha: '/captcha/generate',
    getCaptchaForRegister: '/registerCaptcha/captcha/generate',
    internationalKyc: '/shufti/kyc/onsite/verification',
    updateIntlKycStatus: '/shufti/get/kyc/status',
    rocketChatLogout: '/before/logout',
    getContactDesList: 'onboard/get/designation/list',
    getContactList: 'onboard/get/client/contactdetails',
    setContact: 'onboard/saveupdate/client/contact/details',
    deleteContact: '/onboard/delete/client/contacts',
    getContactlist: '/onboard/get/client/contactdetails',
    setDocument: 'onboard/upload/company/docs',
    getDocList: '/onboard/get/company/docs',
    deleteDoc: 'onboard/delete/company/docs',
    getCompanyList: 'client/get/list',
    searchCompanyList: 'client/get/list',
    getSortedCompanyList: 'client/get/list',
    getCompanyDetails: 'client/get/details',
    getCompanyCampaignList: 'client/get/campaigns',
    orderIdWallet: 'razorpay/create/order?requestOrder=wallet',
    getCompanyVulList: 'client/get/vulList',
    walletUpdatePayment: '/razorpay/save/payment/details?requestOrder=wallet',
    getPaymentlist: '/payment/company/wallet/tx/list',
    updateStatus: 'onboard/update/company/docs/status',
    updateStatusContact: 'onboard/update/client/contact/status',
    setRole: 'admin/add/custom/role',
    getRoleAccess: 'admin/get/role/access',
    getRolelist: 'admin/get/custom/role',
    deleteRole: 'admin/delete/custom/role',
    setUser: 'admin/register/vulhunt/user',
    getUserAccess: 'admin/get/custom/roles',
    getUserlist: 'admin/get/vulhunt/user/list',
    getUserEdit: 'admin/get/vulhunt/user',
    updateUser: 'admin/update/vulhunt/user',
    deactivateUser: 'admin/deactivate/vulhunt/user',
    getpiechartsrdata: 'dashboard/super/admin/get/total/registered/sr',
    getpiechartcampaigndata: 'dashboard/super/admin/get/total/campaigns/report',
    getpiechartsrexpdata: 'dashboard/super/admin/get/sr/exp/report',
    getpiechartsrkycdata: 'dashboard/super/admin/get/sr/kyc/status/report',
    getpiechartreferaljoineddata: 'dashboard/super/admin/get/referrals/report',
    getReferalBarGraph: 'dashboard/super/admin/get/referrals/vuln/report',
    getCertificateBarGraph:
      'dashboard/super/admin/get/certification/status/report',
    getReportedBarGraph: 'dashboard/super/admin/get/total/vuln/reported/report',
    getRealStatusBarGraph: 'dashboard/super/admin/get/vuln/real/status/report',
    getPaymentRewardBarGraph:
      'dashboard/super/admin/get/payment/pending/report',
    getPaidBarGraph: 'dashboard/super/admin/get/total/rewards/paid/report',
    getcampaignbardata: 'dashboard/rp/get/payment/paid/campaigns',
    getcampaignDuebardata: 'dashboard/rp/get/payment/due/campaigns',
    getTabledata: 'dashboard/rp/get/vuln/list/payment/queue',
    getGroupData: 'dashboard/rp/get/vuln/reviewed/by/group',
    getqueuedData: 'dashboard/rp/get/vuln/queued',
    getreviewedData: 'dashboard/rp/get/vuln/reviewed',
  },
};
